# Example: Base Scenario Configuration

# This config runs the base scenario with default parameters

random_seed: 42
base_churn_rate: 0.05
estimated_cac: 500
projection_months: 12

activity_weights:
  login: 1
  feature_use: 2
  support_ticket: -5

scenarios:
  optimistic:
    growth_multiplier: 1.5
    churn_multiplier: 0.8
  
  pessimistic:
    growth_multiplier: 0.5
    churn_multiplier: 1.5
